name: seeflix_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Jakarta
      fonts:
        - asset: assets/fonts/Jakarta-regular.ttf
        - asset: assets/fonts/Jakarta-italic.ttf
          style: italic

